worker_processes 4;
events { worker_connections 16384; }
http {
    server_tokens off;
    keepalive_requests 100000;
    access_log off;
    server {
        listen 127.0.0.1:18271 http2;
        server_name localhost;
        location /c {
            default_type text/plain;
            echo_read_request_body;
            echo -n "$echo_request_body";
            echo_flush;
        }
    }
}
